# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed2b99fdc97fed0bff278a1af33c4c1e92d5fc02e8f2ed7553943f47d5166d63a175b1341a129b7f59cc2e00e083eaf076cbdae07bb81cabe172085d81fc0d68

test:
  secret_key_base: d7389709563c534ea160c4f2832168d9d5a791f04e2e7f59bcabbccdd2704076d576e9844fed035e120d4ac93496e2e3bc98fbeb531556d4d1e057bd761e8d78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
